name: doordish
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  logger: ^0.8.3
  equatable: ^1.0.0
  js: ^0.6.0
  http: ^0.12.0+4
  flutter_google_maps: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/calendar.png
    - assets/icons/faq.png
    - assets/icons/menu.png
    - assets/icons/overview.png
    - assets/icons/testimonial.png
    - assets/icons/transaction.png
    - assets/icons/heart_line.png
    - assets/icons/star_rating.png
    - assets/icons/notification.png
    - assets/icons/notification_active.png
    - assets/icons/profile.png
    - assets/icons/visa_logo_transparent.png
    - assets/icons/edit_button.png
    - assets/icons/bowl.png
    - assets/icons/bread_1.png
    - assets/icons/burger.png
    - assets/icons/chicken_thigh.png
    - assets/icons/coffee.png
    - assets/icons/cooking.png
    - assets/icons/donuts.png
    - assets/icons/french_fries.png
    - assets/icons/sushi_rool.png
    - assets/icons/kiwi.png
    - assets/icons/logo.png
    - assets/icons/female_avatar.png

    - assets/images/meals/bean_soup.png
    - assets/images/meals/cabbage_salad.png
    - assets/images/meals/chicken_soup.png
    - assets/images/meals/vegetable_mix.png
    - assets/images/meals/stewed_vegetables.png
    - assets/images/meals/seafood_soup.png
    - assets/images/meals/noodle_salad.png
    - assets/images/meals/okroshka.png
    - assets/images/meals/roast_potatoes.png
    - assets/images/bg.png
    - assets/images/home_illustration.png
    - assets/images/time_illustration.png
    - assets/images/video.png
    - assets/images/client_logo.png

fonts:
  - family: Helvetica
    fonts:
      - asset: assets/fonts/Helvetica_Bold.ttf
      - asset: assets/fonts/Helvetica_Bold_Oblique.ttf
      - asset: assets/fonts/Helvetica_light.ttf
      - asset: assets/fonts/Helvetica_Oblique.ttf
      - asset: assets/fonts/Helvetica.ttf
